#pragma once

enum Talent : int {
  TALENT_UNKNOWN = 0,
  TALENT_1H,
  TALENT_2H,
  TALENT_BOW,
  TALENT_CROSSBOW,
  TALENT_PICK_LOCKS,
  TALENT_PICKPOCKET_UNUSED, // 6 - relict from Gothic 1 in the scripts
  TALENT_MAGE,
  TALENT_SNEAK,
  TALENT_REGENERATE,
  TALENT_FIREMASTER,
  TALENT_ACROBATIC,
  TALENT_PICKPOCKET, // 12 - actual pickpocket talent used in Gothic 2
  TALENT_SMITH,
  TALENT_RUNES,
  TALENT_ALCHEMY,
  TALENT_THROPHY,
  TALENT_A,
  TALENT_B,
  TALENT_C,
  TALENT_D,
  TALENT_E,
  TALENT_MAX
};

enum SkillWeapon : int {
  WEAPON_1H = 1,
  WEAPON_2H,
  WEAPON_BOW,
  WEAPON_CBOW
};

enum DamageType : int {
  DAMAGE_INVALID = 0,
  DAMAGE_BARRIER = 1,
  DAMAGE_BLUNT = DAMAGE_BARRIER << 1,
  DAMAGE_EDGE = DAMAGE_BLUNT << 1,
  DAMAGE_FIRE = DAMAGE_EDGE << 1,
  DAMAGE_FLY = DAMAGE_FIRE << 1,
  DAMAGE_MAGIC = DAMAGE_FLY << 1,
  DAMAGE_POINT = DAMAGE_MAGIC << 1,
  DAMAGE_FALL = DAMAGE_POINT << 1
};

enum ItemFlag : int {
  ITEM_CAT_NONE = 0,
  ITEM_CAT_NF = 1 << 0,
  ITEM_CAT_FF = 1 << 1,
  ITEM_CAT_MUN = 1 << 2,
  ITEM_CAT_ARMOR = 1 << 3,
  ITEM_CAT_FOOD = 1 << 4,
  ITEM_CAT_DOCS = 1 << 5,
  ITEM_CAT_POTION = 1 << 6,
  ITEM_CAT_LIGHT = 1 << 7,
  ITEM_CAT_RUNE = 1 << 8,
  ITEM_CAT_MAGIC = 1 << 9,
  ITEM_FLAG_DAG = 1 << 10,
  ITEM_FLAG_SWD = 1 << 11,
  ITEM_FLAG_AXE = 1 << 12,
  ITEM_FLAG_2HD_SWD = 1 << 13,
  ITEM_FLAG_2HD_AXE = 1 << 14,
  ITEM_FLAG_SHIELD = 1 << 15,
  ITEM_FLAG_BOW = 1 << 16,
  ITEM_FLAG_CROSSBOW = 1 << 17,
  ITEM_FLAG_RING = 1 << 18,
  ITEM_FLAG_AMULET = 1 << 19,
  ITEM_FLAG_BELT = 1 << 20,
  ITEM_FLAG_DROPPED = 1 << 21,
  ITEM_FLAG_MI = 1 << 22,
  ITEM_FLAG_MULTI = 1 << 23,
  ITEM_FLAG_NFOCUS = 1 << 24,
  ITEM_FLAG_CREATEAMMO = 1 << 25,
  ITEM_FLAG_NSPLIT = 1 << 26,
  ITEM_FLAG_DRINK = 1 << 27,
  ITEM_FLAG_TORCH = 1 << 28,
  ITEM_FLAG_THROW = 1 << 29,
  ITEM_FLAG_ACTIVE = 1 << 30
};

enum ItemWear : int {
  ITEM_WEAR_NO = 0,
  ITEM_WEAR_TORSO,
  ITEM_WEAR_HEAD,
  ITEM_WEAR_LIGHT
};

enum WeaponMode : int {
  WEAPONMODE_NONE = 0,
  WEAPONMODE_FIST,
  WEAPONMODE_DAG,
  WEAPONMODE_1HS,
  WEAPONMODE_2HS,
  WEAPONMODE_BOW,
  WEAPONMODE_CBOW,
  WEAPONMODE_MAG,
  WEAPONMODE_MAX
};