addEventHandler('onKeyDown', function(key)
    if key == KEY_V then
        setPlayerVisual(heroId, "HUM_BODY_NAKED0", 8, "HUM_HEAD_FIGHTER", 26)
		setPlayerFatness(heroId, 5.0)
		setPlayerScale(heroId, 2.5, 0.75, 2.5)
		applyPlayerOverlay(heroId, "HUMANS_RELAXED.MDS")
    elseif key == KEY_H then
        setPlayerMaxHealth(heroId, 150)
        setPlayerHealth(heroId, 120)
        print("Health: " .. getPlayerHealth(heroId) .. "/" .. getPlayerMaxHealth(heroId))
    elseif key == KEY_M then
        setPlayerMaxMana(heroId, 200)
        setPlayerMana(heroId, 75)
        print("Mana: " .. getPlayerMana(heroId) .. "/" .. getPlayerMaxMana(heroId))
    elseif key == KEY_S then
        setPlayerStrength(heroId, 40)
		print("Strength: " .. getPlayerStrength(heroId))
        setPlayerDexterity(heroId, 25)
		print("Dexterity: " .. getPlayerDexterity(heroId))
        setPlayerSkillWeapon(heroId, WEAPON_1H, 80)
		print("Skill 1H: " .. getPlayerSkillWeapon(heroId, WEAPON_1H) .. " | " .. WEAPON_1H)
        setPlayerTalent(heroId, TALENT_BOW, 2)
		print("Talent Bow: " .. getPlayerTalent(heroId, TALENT_BOW) .. " | " .. TALENT_BOW)
        setPlayerTalent(heroId, TALENT_MAGE, 3)
		print("Magic Circle: " .. getPlayerTalent(heroId, TALENT_MAGE) .. " | " .. TALENT_MAGE)
        setPlayerTalent(heroId, TALENT_PICKPOCKET, 1)
		print("Pickpocket: " .. getPlayerTalent(heroId, TALENT_PICKPOCKET) .. " | " .. TALENT_PICKPOCKET)
    elseif key == KEY_P then
		setPlayerWorld(heroId, "COLONY.ZEN")
        setPlayerPosition(heroId, -4577.95752, 720, 738.122925)
		setPlayerAngle(heroId, 180)
        local world = getPlayerWorld(heroId)
        print("Worldpath: " .. world)
        local x, y, z = getPlayerPosition(heroId)
        print("Position: " .. x .. "," .. y .. "," .. z .. "," .. getPlayerAngle(heroId))
    elseif key == KEY_C then
        setPlayerColor(heroId, 0, 200, 255)
        local r, g, b = getPlayerColor(heroId)
        print("Nickname color: " .. r .. "," .. g .. "," .. b)
    elseif key == KEY_E then
        setExp(1250)
        setNextLevelExp(2000)
        print("Experience: " .. getExp() .. "/" .. getNextLevelExp())
        setLearnPoints(20)
        print("Learn points: " .. getLearnPoints())
        setPlayerLevel(30)
        print("Level: " .. getPlayerLevel(heroId))
    end
end)